// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise"
import { OpenAPI } from "./core/OpenAPI"
import { request as __request } from "./core/request"
import type {
  ChatGetUserConversationsResponse,
  ChatCreateConversationData,
  ChatCreateConversationResponse,
  ChatGetProjectConversationsData,
  ChatGetProjectConversationsResponse,
  ChatGetConversationData,
  ChatGetConversationResponse,
  ChatCreateMessageData,
  ChatCreateMessageResponse,
  ChatUpdateConversationTitleData,
  ChatUpdateConversationTitleResponse,
  ChatGenerateConversationTitleData,
  ChatGenerateConversationTitleResponse,
  ChatDeleteConversationData,
  ChatDeleteConversationResponse,
  DocumentsGetDocumentData,
  DocumentsGetDocumentResponse,
  DocumentsUpdateDocumentData,
  DocumentsUpdateDocumentResponse,
  DocumentsDeleteDocumentData,
  DocumentsDeleteDocumentResponse,
  DocumentsGetDocumentProgressData,
  DocumentsGetDocumentProgressResponse,
  DocumentsRetryDocumentProcessingData,
  DocumentsRetryDocumentProcessingResponse,
  ItemsReadItemsData,
  ItemsReadItemsResponse,
  ItemsCreateItemData,
  ItemsCreateItemResponse,
  ItemsReadItemData,
  ItemsReadItemResponse,
  ItemsUpdateItemData,
  ItemsUpdateItemResponse,
  ItemsDeleteItemData,
  ItemsDeleteItemResponse,
  LoginLoginAccessTokenData,
  LoginLoginAccessTokenResponse,
  LoginTestTokenResponse,
  LoginRecoverPasswordData,
  LoginRecoverPasswordResponse,
  LoginResetPasswordData,
  LoginResetPasswordResponse,
  LoginRecoverPasswordHtmlContentData,
  LoginRecoverPasswordHtmlContentResponse,
  PrivateCreateUserData,
  PrivateCreateUserResponse,
  ProjectsCreateProjectData,
  ProjectsCreateProjectResponse,
  ProjectsGetProjectsData,
  ProjectsGetProjectsResponse,
  ProjectsGetProjectData,
  ProjectsGetProjectResponse,
  ProjectsUpdateProjectData,
  ProjectsUpdateProjectResponse,
  ProjectsDeleteProjectData,
  ProjectsDeleteProjectResponse,
  ProjectsGetProjectCapacityData,
  ProjectsGetProjectCapacityResponse,
  ProjectsGetProjectDocumentsData,
  ProjectsGetProjectDocumentsResponse,
  ProjectsUploadDocumentData,
  ProjectsUploadDocumentResponse,
  UsersReadUsersData,
  UsersReadUsersResponse,
  UsersCreateUserData,
  UsersCreateUserResponse,
  UsersReadUserMeResponse,
  UsersDeleteUserMeResponse,
  UsersUpdateUserMeData,
  UsersUpdateUserMeResponse,
  UsersUpdatePasswordMeData,
  UsersUpdatePasswordMeResponse,
  UsersRegisterUserData,
  UsersRegisterUserResponse,
  UsersReadUserByIdData,
  UsersReadUserByIdResponse,
  UsersUpdateUserData,
  UsersUpdateUserResponse,
  UsersDeleteUserData,
  UsersDeleteUserResponse,
  UtilsTestEmailData,
  UtilsTestEmailResponse,
  UtilsHealthCheckResponse,
} from "./types.gen"

export class ChatService {
  /**
   * Get User Conversations
   * Get all conversations for the current user.
   * @returns ChatConversationPublic Successful Response
   * @throws ApiError
   */
  public static getUserConversations(): CancelablePromise<ChatGetUserConversationsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/chat/conversations",
    })
  }

  /**
   * Create Conversation
   * Create a new chat conversation.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ChatConversationPublic Successful Response
   * @throws ApiError
   */
  public static createConversation(
    data: ChatCreateConversationData,
  ): CancelablePromise<ChatCreateConversationResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/chat/conversations",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project Conversations
   * Get all conversations for a project.
   * @param data The data for the request.
   * @param data.projectId
   * @returns ChatConversationPublic Successful Response
   * @throws ApiError
   */
  public static getProjectConversations(
    data: ChatGetProjectConversationsData,
  ): CancelablePromise<ChatGetProjectConversationsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/chat/conversations/{project_id}",
      path: {
        project_id: data.projectId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Conversation
   * Get a conversation by ID with all messages.
   * @param data The data for the request.
   * @param data.conversationId
   * @returns ChatConversationPublic Successful Response
   * @throws ApiError
   */
  public static getConversation(
    data: ChatGetConversationData,
  ): CancelablePromise<ChatGetConversationResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/chat/conversations/{conversation_id}/detail",
      path: {
        conversation_id: data.conversationId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Message
   * Create a new message in a conversation.
   * @param data The data for the request.
   * @param data.conversationId
   * @param data.requestBody
   * @returns ChatMessagePublic Successful Response
   * @throws ApiError
   */
  public static createMessage(
    data: ChatCreateMessageData,
  ): CancelablePromise<ChatCreateMessageResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/chat/conversations/{conversation_id}/messages",
      path: {
        conversation_id: data.conversationId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Conversation Title
   * Update a conversation's title.
   * @param data The data for the request.
   * @param data.conversationId
   * @param data.title
   * @returns ChatConversationPublic Successful Response
   * @throws ApiError
   */
  public static updateConversationTitle(
    data: ChatUpdateConversationTitleData,
  ): CancelablePromise<ChatUpdateConversationTitleResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/chat/conversations/{conversation_id}/title",
      path: {
        conversation_id: data.conversationId,
      },
      query: {
        title: data.title,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Generate Conversation Title
   * Generate a new title for a conversation using AI.
   * @param data The data for the request.
   * @param data.conversationId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static generateConversationTitle(
    data: ChatGenerateConversationTitleData,
  ): CancelablePromise<ChatGenerateConversationTitleResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/chat/conversations/{conversation_id}/generate-title",
      path: {
        conversation_id: data.conversationId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Conversation
   * Delete a conversation and all its messages.
   * @param data The data for the request.
   * @param data.conversationId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteConversation(
    data: ChatDeleteConversationData,
  ): CancelablePromise<ChatDeleteConversationResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/chat/conversations/{conversation_id}",
      path: {
        conversation_id: data.conversationId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class DocumentsService {
  /**
   * Get Document
   * Get a document by ID.
   * @param data The data for the request.
   * @param data.documentId
   * @returns DocumentPublic Successful Response
   * @throws ApiError
   */
  public static getDocument(
    data: DocumentsGetDocumentData,
  ): CancelablePromise<DocumentsGetDocumentResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/documents/{document_id}",
      path: {
        document_id: data.documentId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Document
   * Update a document's metadata.
   * @param data The data for the request.
   * @param data.documentId
   * @param data.requestBody
   * @returns DocumentPublic Successful Response
   * @throws ApiError
   */
  public static updateDocument(
    data: DocumentsUpdateDocumentData,
  ): CancelablePromise<DocumentsUpdateDocumentResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/documents/{document_id}",
      path: {
        document_id: data.documentId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Document
   * Delete a document and its embeddings.
   * @param data The data for the request.
   * @param data.documentId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteDocument(
    data: DocumentsDeleteDocumentData,
  ): CancelablePromise<DocumentsDeleteDocumentResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/documents/{document_id}",
      path: {
        document_id: data.documentId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Document Progress
   * Get processing progress for a document.
   * @param data The data for the request.
   * @param data.documentId
   * @returns DocumentProgress Successful Response
   * @throws ApiError
   */
  public static getDocumentProgress(
    data: DocumentsGetDocumentProgressData,
  ): CancelablePromise<DocumentsGetDocumentProgressResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/documents/{document_id}/progress",
      path: {
        document_id: data.documentId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Retry Document Processing
   * Retry processing a failed document.
   * @param data The data for the request.
   * @param data.documentId
   * @returns DocumentPublic Successful Response
   * @throws ApiError
   */
  public static retryDocumentProcessing(
    data: DocumentsRetryDocumentProcessingData,
  ): CancelablePromise<DocumentsRetryDocumentProcessingResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/documents/{document_id}/retry",
      path: {
        document_id: data.documentId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class ItemsService {
  /**
   * Read Items
   * Retrieve items.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns ItemsPublic Successful Response
   * @throws ApiError
   */
  public static readItems(
    data: ItemsReadItemsData = {},
  ): CancelablePromise<ItemsReadItemsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/items/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Item
   * Create new item.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ItemPublic Successful Response
   * @throws ApiError
   */
  public static createItem(
    data: ItemsCreateItemData,
  ): CancelablePromise<ItemsCreateItemResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/items/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Item
   * Get item by ID.
   * @param data The data for the request.
   * @param data.id
   * @returns ItemPublic Successful Response
   * @throws ApiError
   */
  public static readItem(
    data: ItemsReadItemData,
  ): CancelablePromise<ItemsReadItemResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/items/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Item
   * Update an item.
   * @param data The data for the request.
   * @param data.id
   * @param data.requestBody
   * @returns ItemPublic Successful Response
   * @throws ApiError
   */
  public static updateItem(
    data: ItemsUpdateItemData,
  ): CancelablePromise<ItemsUpdateItemResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/items/{id}",
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Item
   * Delete an item.
   * @param data The data for the request.
   * @param data.id
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteItem(
    data: ItemsDeleteItemData,
  ): CancelablePromise<ItemsDeleteItemResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/items/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class LoginService {
  /**
   * Login Access Token
   * OAuth2 compatible token login, get an access token for future requests
   * @param data The data for the request.
   * @param data.formData
   * @returns Token Successful Response
   * @throws ApiError
   */
  public static loginAccessToken(
    data: LoginLoginAccessTokenData,
  ): CancelablePromise<LoginLoginAccessTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/access-token",
      formData: data.formData,
      mediaType: "application/x-www-form-urlencoded",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Test Token
   * Test access token
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static testToken(): CancelablePromise<LoginTestTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/test-token",
    })
  }

  /**
   * Recover Password
   * Password Recovery
   * @param data The data for the request.
   * @param data.email
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static recoverPassword(
    data: LoginRecoverPasswordData,
  ): CancelablePromise<LoginRecoverPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/password-recovery/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Reset Password
   * Reset password
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static resetPassword(
    data: LoginResetPasswordData,
  ): CancelablePromise<LoginResetPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/reset-password/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Recover Password Html Content
   * HTML Content for Password Recovery
   * @param data The data for the request.
   * @param data.email
   * @returns string Successful Response
   * @throws ApiError
   */
  public static recoverPasswordHtmlContent(
    data: LoginRecoverPasswordHtmlContentData,
  ): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/password-recovery-html-content/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class PrivateService {
  /**
   * Create User
   * Create a new user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static createUser(
    data: PrivateCreateUserData,
  ): CancelablePromise<PrivateCreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/private/users/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class ProjectsService {
  /**
   * Create Project
   * Create a new project.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ProjectPublic Successful Response
   * @throws ApiError
   */
  public static createProject(
    data: ProjectsCreateProjectData,
  ): CancelablePromise<ProjectsCreateProjectResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/projects",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Projects
   * Get all projects for the current user.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns ProjectsPublic Successful Response
   * @throws ApiError
   */
  public static getProjects(
    data: ProjectsGetProjectsData = {},
  ): CancelablePromise<ProjectsGetProjectsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/projects",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project
   * Get a project by ID.
   * @param data The data for the request.
   * @param data.projectId
   * @returns ProjectPublic Successful Response
   * @throws ApiError
   */
  public static getProject(
    data: ProjectsGetProjectData,
  ): CancelablePromise<ProjectsGetProjectResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/projects/{project_id}",
      path: {
        project_id: data.projectId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Project
   * Update a project.
   * @param data The data for the request.
   * @param data.projectId
   * @param data.requestBody
   * @returns ProjectPublic Successful Response
   * @throws ApiError
   */
  public static updateProject(
    data: ProjectsUpdateProjectData,
  ): CancelablePromise<ProjectsUpdateProjectResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/projects/{project_id}",
      path: {
        project_id: data.projectId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Project
   * Delete a project and all its documents and conversations.
   * @param data The data for the request.
   * @param data.projectId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteProject(
    data: ProjectsDeleteProjectData,
  ): CancelablePromise<ProjectsDeleteProjectResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/projects/{project_id}",
      path: {
        project_id: data.projectId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project Capacity
   * Get capacity information for a project.
   * @param data The data for the request.
   * @param data.projectId
   * @returns ProjectCapacity Successful Response
   * @throws ApiError
   */
  public static getProjectCapacity(
    data: ProjectsGetProjectCapacityData,
  ): CancelablePromise<ProjectsGetProjectCapacityResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/projects/{project_id}/capacity",
      path: {
        project_id: data.projectId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project Documents
   * Get all documents for a project.
   * @param data The data for the request.
   * @param data.projectId
   * @returns DocumentsPublic Successful Response
   * @throws ApiError
   */
  public static getProjectDocuments(
    data: ProjectsGetProjectDocumentsData,
  ): CancelablePromise<ProjectsGetProjectDocumentsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/projects/{project_id}/documents",
      path: {
        project_id: data.projectId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Upload Document
   * Upload a document to a project.
   * @param data The data for the request.
   * @param data.projectId
   * @param data.formData
   * @returns DocumentPublic Successful Response
   * @throws ApiError
   */
  public static uploadDocument(
    data: ProjectsUploadDocumentData,
  ): CancelablePromise<ProjectsUploadDocumentResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/projects/{project_id}/documents",
      path: {
        project_id: data.projectId,
      },
      formData: data.formData,
      mediaType: "multipart/form-data",
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UsersService {
  /**
   * Read Users
   * Retrieve users.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns UsersPublic Successful Response
   * @throws ApiError
   */
  public static readUsers(
    data: UsersReadUsersData = {},
  ): CancelablePromise<UsersReadUsersResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create User
   * Create new user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static createUser(
    data: UsersCreateUserData,
  ): CancelablePromise<UsersCreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read User Me
   * Get current user.
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/me",
    })
  }

  /**
   * Delete User Me
   * Delete own user.
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/me",
    })
  }

  /**
   * Update User Me
   * Update own user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUserMe(
    data: UsersUpdateUserMeData,
  ): CancelablePromise<UsersUpdateUserMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Password Me
   * Update own password.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static updatePasswordMe(
    data: UsersUpdatePasswordMeData,
  ): CancelablePromise<UsersUpdatePasswordMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me/password",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Register User
   * Create new user without the need to be logged in.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static registerUser(
    data: UsersRegisterUserData,
  ): CancelablePromise<UsersRegisterUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/signup",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read User By Id
   * Get a specific user by id.
   * @param data The data for the request.
   * @param data.userId
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static readUserById(
    data: UsersReadUserByIdData,
  ): CancelablePromise<UsersReadUserByIdResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update User
   * Update a user.
   * @param data The data for the request.
   * @param data.userId
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUser(
    data: UsersUpdateUserData,
  ): CancelablePromise<UsersUpdateUserResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete User
   * Delete a user.
   * @param data The data for the request.
   * @param data.userId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUser(
    data: UsersDeleteUserData,
  ): CancelablePromise<UsersDeleteUserResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UtilsService {
  /**
   * Test Email
   * Test emails.
   * @param data The data for the request.
   * @param data.emailTo
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static testEmail(
    data: UtilsTestEmailData,
  ): CancelablePromise<UtilsTestEmailResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/utils/test-email/",
      query: {
        email_to: data.emailTo,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Health Check
   * @returns HealthCheck Successful Response
   * @throws ApiError
   */
  public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/utils/health-check/",
    })
  }
}
