// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type Body_projects_upload_document = {
  file: Blob | File
  document_type?: string
}

export type ChatConversationCreate = {
  title: string
  use_documents?: boolean
  project_id?: string | null
}

export type ChatConversationPublic = {
  title: string
  use_documents?: boolean
  id: string
  user_id: string
  project_id?: string | null
  auto_generated_title?: boolean
  title_generation_task_id?: string | null
  created_at: string
  updated_at: string
  messages?: Array<ChatMessagePublic>
}

export type ChatMessageCreate = {
  role: string
  content: string
  use_documents?: boolean
  document_references?: Array<DocumentReferenceBase>
}

export type ChatMessagePublic = {
  role: string
  content: string
  use_documents?: boolean
  document_references?: Array<DocumentReferencePublic>
  id: string
  conversation_id: string
  created_at: string
}

/**
 * Schema for document processing progress.
 */
export type DocumentProgress = {
  document_id: string
  status: DocumentStatus
  total_chunks: number
  processed_chunks: number
  progress_percentage: number
  error_message?: string | null
}

/**
 * Schema for Document in API responses.
 */
export type DocumentPublic = {
  filename: string
  file_type: string
  document_type?: string
  id: string
  project_id: string
  file_size: number
  status: DocumentStatus
  error_message?: string | null
  total_chunks: number
  processed_chunks: number
  estimated_tokens: number
  task_id?: string | null
  uploaded_at: string
  processing_started_at?: string | null
  processing_completed_at?: string | null
}

export type DocumentReferenceBase = {
  document_id: string
  document_type: string
  filename: string
  content_snippet: string
  relevance_score: number
  page_number: number
  page_total: number
}

export type DocumentReferencePublic = {
  document_id: string
  document_type: string
  filename: string
  content_snippet: string
  relevance_score: number
  page_number: number
  page_total: number
  id: string
  message_id: string
  created_at: string
}

/**
 * Schema for list of documents.
 */
export type DocumentsPublic = {
  data: Array<DocumentPublic>
  count: number
}

/**
 * Status of document processing.
 */
export type DocumentStatus = "pending" | "processing" | "completed" | "failed"

/**
 * Schema for updating a document.
 */
export type DocumentUpdate = {
  document_type?: string | null
}

/**
 * Health check response schema.
 */
export type HealthCheck = {
  status: string
  version: string
  message: string
  deployment: string
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ItemCreate = {
  title: string
  description?: string | null
}

export type ItemPublic = {
  title: string
  description?: string | null
  id: string
  owner_id: string
}

export type ItemsPublic = {
  data: Array<ItemPublic>
  count: number
}

export type ItemUpdate = {
  title?: string | null
  description?: string | null
}

export type Message = {
  message: string
}

export type NewPassword = {
  token: string
  new_password: string
}

export type PrivateUserCreate = {
  email: string
  password: string
  full_name: string
  is_verified?: boolean
}

/**
 * Schema for project capacity information.
 */
export type ProjectCapacity = {
  documents_tokens: number
  conversations_tokens: number
  total_tokens: number
  max_tokens: number
  usage_percentage: number
  remaining_tokens: number
  is_near_limit: boolean
  is_over_limit: boolean
}

/**
 * Schema for creating a new project.
 */
export type ProjectCreate = {
  name: string
  description?: string | null
  system_prompt?: string | null
  max_context_tokens?: number
}

/**
 * Schema for Project in API responses.
 */
export type ProjectPublic = {
  name: string
  description?: string | null
  system_prompt?: string | null
  max_context_tokens?: number
  id: string
  user_id: string
  created_at: string
  updated_at: string
  documents?: Array<DocumentPublic>
  capacity?: ProjectCapacity | null
}

/**
 * Schema for list of projects.
 */
export type ProjectsPublic = {
  data: Array<ProjectPublic>
  count: number
}

/**
 * Schema for updating a project.
 */
export type ProjectUpdate = {
  name?: string | null
  description?: string | null
  system_prompt?: string | null
  max_context_tokens?: number | null
}

export type Token = {
  access_token: string
  token_type?: string
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserCreate = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password: string
}

export type UserPublic = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  id: string
}

export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
}

export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

export type UserUpdate = {
  email?: string | null
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password?: string | null
}

export type UserUpdateMe = {
  full_name?: string | null
  email?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type ChatGetUserConversationsResponse = Array<ChatConversationPublic>

export type ChatCreateConversationData = {
  requestBody: ChatConversationCreate
}

export type ChatCreateConversationResponse = ChatConversationPublic

export type ChatGetProjectConversationsData = {
  projectId: string
}

export type ChatGetProjectConversationsResponse = Array<ChatConversationPublic>

export type ChatGetConversationData = {
  conversationId: string
}

export type ChatGetConversationResponse = ChatConversationPublic

export type ChatCreateMessageData = {
  conversationId: string
  requestBody: ChatMessageCreate
}

export type ChatCreateMessageResponse = ChatMessagePublic

export type ChatUpdateConversationTitleData = {
  conversationId: string
  title: string
}

export type ChatUpdateConversationTitleResponse = ChatConversationPublic

export type ChatGenerateConversationTitleData = {
  conversationId: string
}

export type ChatGenerateConversationTitleResponse = Message

export type ChatDeleteConversationData = {
  conversationId: string
}

export type ChatDeleteConversationResponse = Message

export type DocumentsGetDocumentData = {
  documentId: string
}

export type DocumentsGetDocumentResponse = DocumentPublic

export type DocumentsUpdateDocumentData = {
  documentId: string
  requestBody: DocumentUpdate
}

export type DocumentsUpdateDocumentResponse = DocumentPublic

export type DocumentsDeleteDocumentData = {
  documentId: string
}

export type DocumentsDeleteDocumentResponse = Message

export type DocumentsGetDocumentProgressData = {
  documentId: string
}

export type DocumentsGetDocumentProgressResponse = DocumentProgress

export type DocumentsRetryDocumentProcessingData = {
  documentId: string
}

export type DocumentsRetryDocumentProcessingResponse = DocumentPublic

export type ItemsReadItemsData = {
  limit?: number
  skip?: number
}

export type ItemsReadItemsResponse = ItemsPublic

export type ItemsCreateItemData = {
  requestBody: ItemCreate
}

export type ItemsCreateItemResponse = ItemPublic

export type ItemsReadItemData = {
  id: string
}

export type ItemsReadItemResponse = ItemPublic

export type ItemsUpdateItemData = {
  id: string
  requestBody: ItemUpdate
}

export type ItemsUpdateItemResponse = ItemPublic

export type ItemsDeleteItemData = {
  id: string
}

export type ItemsDeleteItemResponse = Message

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type LoginRecoverPasswordHtmlContentData = {
  email: string
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type PrivateCreateUserData = {
  requestBody: PrivateUserCreate
}

export type PrivateCreateUserResponse = UserPublic

export type ProjectsCreateProjectData = {
  requestBody: ProjectCreate
}

export type ProjectsCreateProjectResponse = ProjectPublic

export type ProjectsGetProjectsData = {
  limit?: number
  skip?: number
}

export type ProjectsGetProjectsResponse = ProjectsPublic

export type ProjectsGetProjectData = {
  projectId: string
}

export type ProjectsGetProjectResponse = ProjectPublic

export type ProjectsUpdateProjectData = {
  projectId: string
  requestBody: ProjectUpdate
}

export type ProjectsUpdateProjectResponse = ProjectPublic

export type ProjectsDeleteProjectData = {
  projectId: string
}

export type ProjectsDeleteProjectResponse = Message

export type ProjectsGetProjectCapacityData = {
  projectId: string
}

export type ProjectsGetProjectCapacityResponse = ProjectCapacity

export type ProjectsGetProjectDocumentsData = {
  projectId: string
}

export type ProjectsGetProjectDocumentsResponse = DocumentsPublic

export type ProjectsUploadDocumentData = {
  formData: Body_projects_upload_document
  projectId: string
}

export type ProjectsUploadDocumentResponse = DocumentPublic

export type UsersReadUsersData = {
  limit?: number
  skip?: number
}

export type UsersReadUsersResponse = UsersPublic

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = UserPublic

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type UsersUpdatePasswordMeResponse = Message

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersReadUserByIdData = {
  userId: string
}

export type UsersReadUserByIdResponse = UserPublic

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  userId: string
}

export type UsersUpdateUserResponse = UserPublic

export type UsersDeleteUserData = {
  userId: string
}

export type UsersDeleteUserResponse = Message

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsHealthCheckResponse = HealthCheck
